config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :images
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :relationships
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :user
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :imager, presence: true
  mount_uploader :imager, ImagerUploader
  after_create :send_email
  after_create :send_text_message

  def self.add_view(image)
    image.update_attributes(:views => image.views + 1)
  end

  def available?(u)
    return true if !private?
    self.user == u
  end

  def send_email
    PhotoMailer.photo_email(self.user).deliver
  end

  def send_text_message
    @twilio_client = Twilio::REST::Client.new ENV['twilio_sid'], ENV['twilio_token']

    @twilio_client.messages.create(
      :from => "+1#{ENV['twilio_phone_number']}",
      :to => ENV['dylan_phone'],
      :body => "This is an message. It gets sent to Dylan"
    )
  end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :images
  has_many :active_relationships,   class_name: "Relationship",
                                    foreign_key: "follower_id"
  has_many :passive_relationships,  class_name: "Relationship",
                                    foreign_key: "followed_id"
  has_many :following, through: :active_relationships,  source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  validates :name, presence: true
  validates :email, presence: true 
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  has_secure_password

  def feed
    following_ids = "SELECT followed_id FROM relationships
                     WHERE  follower_id = :user_id"
    Image.where("user_id IN (#{following_ids})
                     OR user_id = :user_id", user_id: id)
  end

  def follow(other_user)
    following << other_user
  end

  def unfollow(other_user)
    following.delete(other_user)
  end

  def following?(other_user)
    following.include?(other_user)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController

  def create
    @image = current_user.images.build(image_params)
    if @image.save
      redirect_to root_path
    else
      render root_path
    end
  end

  def show
    @image = Image.find(params[:id])
    @views = @image.views
    Image.add_view @image
  end

  private

  def image_params
    params.require(:image).permit(:content, :imager, :private)
  end

end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
    user = User.find(params[:followed_id])
    current_user.follow(user)
    redirect_to user
  end

  def destroy
  end
end

app/controllers/send_text_controller.rb
class SendTextController < ApplicationController
  def index
  end

  def send_text_message
    number_to_send_to = params[:number_to_send_to]

    twilio_sid = "abc123"
    twilio_token = "foobar"
    twilio_phone_number = "6165555555"

    @twilio_client = Twilio::REST::Client.new twilio_sid, twilio_token

    @twilio_client.account.sms.messages.create(
      :from => "+1#{twilio_phone_number}",
      :to => number_to_send_to,
      :body => "This is an message. It gets sent to #{number_to_send_to}"
    )
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    if current_user
      redirect_to current_user
    end
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in(user)
      redirect_to root_path
    else
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to login_path
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if logged_in?
      @image = current_user.images.build
      @feed_items = current_user.feed.paginate(page: params[:page])
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @feed_items = @user.images
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      log_in @user
      redirect_to root_path
    else
      render 'new'
    end
  end

  def following
    @user  = User.find(params[:id])
    @users = @user.following.paginate(page: params[:page])
    render 'show_follow'
  end

  def followers
    @user  = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page])
    render 'show_follow'
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/send_text_helper.rb
module SendTextHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def current_user?(user)
    user == current_user
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/images/_image.html.erb
<%= image.content %>

app/views/images/show.html.erb
<%= image_tag @image.imager %>
<%= @views %>

app/views/layouts/_header.html.erb
<% if logged_in? %>
  <%= link_to current_user.name, root_path %>
  <%= link_to "Log out", logout_path, method: :delete %>
<% else %>
  <%= link_to "Log in", login_path %>
  <%= link_to "Sign up", new_user_path %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CanadaPhoto</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
  </body>
</html>

app/views/shared/_feed.html.erb
<% if @feed_items.try(:any?) %>
  <% @feed_items.each do |image| %>
    <% if image.available?(current_user) %>
      <%= link_to image.user.name, user_path(id: image.user.id) %>
      <%= link_to image_path image do %>
        <%= image_tag image.imager.feed  %>
      <% end %>
      <%= time_ago_in_words(image.created_at) %> ago
    <% end %>
  <% end %>
<% end %>

app/views/shared/_follow_form.html.erb
<% unless current_user(@user) %>

  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
<% end %>

app/views/shared/_image_form.html.erb
<% if logged_in? %>
  <%= form_for(@image) do |f| %>
    <%= f.text_field :content %>
    <%= f.file_field :imager %>

    <%= f.label :private %>
    <%= f.check_box :private %>
    <%= f.submit "New Picture"%>
  <% end %>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<% if logged_in? %>
  <%= link_to following_user_path @user do %>
    <%= @user.following.count %> 
  <% end %> following
  <%= link_to followers_user_path @user do %>
    <%= @user.followers.count %>
  <% end %> followers
<% end %>

app/views/static_pages/home.html.erb
<%= render 'shared/image_form' %>
<%= render 'shared/stats' %>
<%= render 'shared/feed' %>

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build) do |f| %>
  <%= hidden_field_tag :followed_id, @user.id %>
  <%= f.submit "Follow" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>

  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
              html: {method: :delete} ) do |f| %>
  <%= f.submit "Unfollow" %>
<% end %>

app/views/users/index.html.erb
<% @users.each do |user| %>
  <%= link_to user.name, user %>
  
<% end %>

app/views/users/new.html.erb
<%= form_for @user do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :email %>
  <%= f.text_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>

  <%= f.submit %>
<% end %>

app/views/users/show.html.erb
<%= render 'shared/feed' %>
<%= render 'shared/stats' %>
<%= render 'follow_form' if logged_in? %>

app/views/users/show_follow.html.erb
<% if @users.any? %>
  <% @users.each do |user| %>
    <%= link_to user.name, user %>
  <% end %>
<% end %>